app:
  access-type: ORM
  message-transport: KAFKA
  batch-size: 100
  scheduler:
    interval: 30000
    thread-count: 4
  github:
    token: ${GITHUB_TOKEN} # env variable
    base-url: https://api.github.com
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
    base-url: https://api.stackexchange.com/2.3
  update-events:
    topic: updates
    dlq-topic: updates-dlq
    partitions: 1
    replicas: 1

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: password
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:19092
    producer.properties:
      acks: 1
      batch.size: 1024
      linger.ms: 10000
    cloud.zookeeper:
      config.enabled: false
      connect-string: localhost:2181

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  structured:
    format:
      file: ecs
  file:
    name: log.json
