app:
  access-type: ORM
  message-transport: KAFKA
  batch-size: 100
  scheduler:
    interval: 30000
    thread-count: 4
  github:
    token: ${GITHUB_TOKEN} # env variable
    base-url: https://api.github.com
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
    base-url: https://api.stackexchange.com/2.3
  ticketpro:
    base-url: https://www.ticketpro.by
  update-events:
    topic: updates
    dlq-topic: updates-dlq
    partitions: 1
    replicas: 1

spring:
  application:
    name: Scrapper
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/scrapper}
    username: postgres
    password: password
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    producer.properties:
      acks: 1
      batch.size: 1024
      linger.ms: 10000
    cloud.zookeeper:
      config.enabled: false
      connect-string: localhost:2181
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 400ms
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.InternalServerError
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException.GatewayTimeout
          - java.net.ConnectException
        exponential-backoff-multiplier: 2
        enable-exponential-backoff: true
    instances:
      botClient:
        base-config: default
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 100
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 3s
        permitted-number-of-calls-in-half-open-state: 1
        sliding-window-size: 1
        minimum-number-of-calls: 1
        wait-duration-in-open-state: 3s
        automatic-transition-from-open-to-half-open-enabled: false
    instances:
      botClient:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: false
    instances:
      botClient:
        base-config: default

bucket:
  capacity: 10
  duration: 1m

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
      base-path: /
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        custom_scrape_time: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        custom_scrape_time: 0.5,0.95,0.99

bot:
  base-url: ${BOT_BASE_URL:http://localhost:8080}

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  structured:
    format:
      file: ecs
  file:
    name: logs/log.json
