package backend.academy.bot.dialog;

public enum TrackState {
    AWAITING_URL,
    AWAITING_TAGS,
    AWAITING_FILTERS,
    AWAITING_TAG,
    AWAITING_FILTER,
    AWAITING_NOTIFICATION_MODE,
    AWAITING_NOTIFICATION_TIME,
    COMPLETED,
}
